
pub DescriptorType: DescriptorType = {
    <label:LabelType> <props:PropertyType> => DescriptorType::new(label, props),
    <label:LabelType> => DescriptorType::with_label(label),
    <props:PropertyType> => DescriptorType::with_properties(props),
};

pub Descriptor: Descriptor = {
    <var:Name> ":" <ty:DescriptorType> => Descriptor::new(var.into(), ty),
    ":" <ty:DescriptorType> => Descriptor::with_type(ty),
    <var:Name> => Descriptor::with_variable(var.into()),
    => Descriptor::default(),
};

