pub Expr: Expr = {
    #[precedence(level="5")] #[assoc(side="left")]
    <l:Expr> AND <r:Expr> => Expr::binop(BinOpKind::And, l, r),
    <l:Expr> OR <r:Expr> => Expr::binop(BinOpKind::Or, l, r),
    
    #[precedence(level="4")] #[assoc(side="left")]
    <l:Expr> "<" <r:Expr> => Expr::binop(BinOpKind::Lt, l, r),
    <l:Expr> ">" <r:Expr> => Expr::binop(BinOpKind::Gt, l, r),
    <l:Expr> "<=" <r:Expr> => Expr::binop(BinOpKind::Le, l, r),
    <l:Expr> ">=" <r:Expr> => Expr::binop(BinOpKind::Ge, l, r),
    <l:Expr> "=" <r:Expr> => Expr::binop(BinOpKind::Eq, l, r),
    <l:Expr> IS <r:Expr> => Expr::binop(BinOpKind::Is, l, r),
    <l:Expr> AS <r:Expr> => Expr::binop(BinOpKind::As, l, r),
    
    #[precedence(level="3")] #[assoc(side="left")]
    <l:Expr> "+" <r:Expr> => Expr::binop(BinOpKind::Add, l, r),
    <l:Expr> "-" <r:Expr> => Expr::binop(BinOpKind::Sub, l, r),
    
    #[precedence(level="2")] #[assoc(side="left")]
    <l:Expr> "*" <r:Expr> => Expr::binop(BinOpKind::Mul, l, r),
    <l:Expr> "/" <r:Expr> => Expr::binop(BinOpKind::Div, l, r),
    
    #[precedence(level="1")]
    NOT <e:Expr> => Expr::unop(UnOpKind::Not, e),
    "-" <e:Expr> => Expr::unop(UnOpKind::Neg, e),
    
    #[precedence(level="0")]
    <ExprPrimary>,
};

ExprPrimary: Expr = {
    <ExprConstant> => Expr::Constant(<>),
    <v:Name> "." <a:Name> => Expr::attr_lookup(v.into(), a.into()),
    <SimpleType> => Expr::TypeLiteral(<>),
    "(" <Expr> ")",
};

ExprConstant: Constant = {
    <Number> => <>.into(),
    <Boolean> => <>.into(),
    <String> => <>.into(),
};

String: String = {
    r#"'[^']*'"# => {
        let s = <>;
        s[1..s.len()-1].to_string()
    },
};

Boolean: bool = {
    TRUE => true,
    FALSE => false,
};

Number: i64 = r"\d+" => <>.parse().unwrap();

AND: () = { "and", "AND" };
OR: () = { "or", "OR" };
NOT: () = { "not", "NOT" };
IS: () = { "is", "IS" };
AS: () = { "as", "AS" };

TRUE: () = { "true", "TRUE" };
FALSE: () = { "false", "FALSE" };
