
pub LabelType: LabelType = {
    #[precedence(level="2")] #[assoc(side="left")]
    <l:LabelType> "|" <r:LabelType> => LabelType::Or(Box::new(l), Box::new(r)),
    
    #[precedence(level="1")] #[assoc(side="left")]
    <l:LabelType> "&" <r:LabelType> => LabelType::And(Box::new(l), Box::new(r)),
    
    #[precedence(level="0")]
    "*" => LabelType::Star,
    <Name> => LabelType::Label(<>),
    "(" <LabelType> ")",
};

